# Generated by Django 3.2.18 on 2023-04-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('adafruit', 'Adafruit')], max_length=20)),
                ('shop_branch', models.CharField(default='', help_text='The branch of the primary shop, i.e. DE or CO.JP for Amazon, or elfadistrelec.no for Distrelec.', max_length=50)),
                ('date', models.DateTimeField(verbose_name='order date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_scraper.order')),
            ],
        ),
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('datasheet', 'Datasheet'), ('item_pdf', 'Scraped Item PDF'), ('item_pdf', 'Scraped Item HTML'), ('item_thumnail', 'Thumbnail'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('filetype', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
