# Generated by Django 3.2.18 on 2023-04-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('datasheet', 'Datasheet'), ('scrape', 'Scraped page'), ('thumnail', 'Thumbnail'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('filetype', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('adafruit', 'Adafruit')], max_length=30)),
                ('shop_branch', models.CharField(default='', help_text='The branch of the primary shop, i.e. DE or CO.JP for Amazon, or elfadistrelec.no for Distrelec.', max_length=50)),
                ('order_id', models.CharField(default='', help_text='The original order id from the shop. Not to be cofused with the internal database id.', max_length=100, verbose_name='the original shop order id')),
                ('date', models.DateTimeField(verbose_name='order date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_id', models.CharField(default='', help_text='The original item id from the shop. Not to be cofused with the internal database id.', max_length=100, verbose_name='the original shop item id')),
                ('count', models.PositiveIntegerField(verbose_name='number of items')),
                ('url', models.URLField(verbose_name='url')),
                ('extra_data', models.JSONField(default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_scraper.order')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_scraper.attachement')),
            ],
        ),
    ]
