# Generated by Django 3.2.18 on 2023-04-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('shop', 'shop_branch', 'order_id'), name='unique_shop_branch_order_id'),
        ),
    ]
