# Generated by Django 3.2.18 on 2023-04-12 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('order_scraper', '0002_order_unique_shop_branch_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='attachement',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'order_scraper'), ('model', 'order')), models.Q(('app_label', 'order_scraper'), ('model', 'orderitem')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='attachement',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop_branch',
            field=models.CharField(blank=True, default='', help_text='The branch of the primary shop, i.e. DE or CO.JP for Amazon, or elfadistrelec.no for Distrelec.', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='thumbnail',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order_scraper.attachement'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
    ]
